# Generated by Django 2.1.7 on 2020-04-01 10:40

from django.conf import settings
import django.contrib.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('api_key', models.CharField(max_length=50, verbose_name='Ключ API')),
                ('owner', models.ForeignKey(on_delete=models.SET(django.contrib.auth.get_user_model), related_name='my_cars', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
    ]
