# Generated by Django 2.1.7 on 2020-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
